version: "3.7"
services:
  app:
    build: ./
    environment:
      - NR_DB_CONNECTION=postgresql://postgres@db:5432
    ports:
      - 8000:8000
  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
